---
title: "Leaflet map"
author: "Charles T. Gray"
date: "23 April 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(tidyverse)
library(eviatlas)
library(htmltools)
library(leaflet)

# qpal - for colour conversion

```


```{r}
# Okay, so this works.

pilotdata %>% 
  leaflet() %>% 
  addTiles()  %>% 
  addMarkers(lng = ~lngplot,
             lat = ~latplot)

```

## Add tooltips

```{r popups one label}
# Works with Year but doesn't work with Citation. Why?

pilotdata %>% 
  leaflet() %>% 
  addTiles()  %>%  
  addMarkers(lng = ~lngplot,
             lat = ~latplot,
             popup = ~paste(Year))  


```

```{r popups more than one label}

# This works.
pilotdata %>% 
  leaflet() %>% 
  addTiles()  %>%  
  addMarkers(lng = ~lngplot,
             lat = ~latplot,
             popup = ~paste(Year, "test"))  

  

```

```{r}
pilotdata %>% 
  leaflet() %>% 
  addTiles()  %>%  
  addMarkers(lng = ~lngplot,
             lat = ~latplot,
             popup = ~paste(Year, "test", Year))  



```

```{r}

pilotdata %>% 
  leaflet() %>% 
  addTiles()  %>%  
  addMarkers(lng = ~lngplot,
             lat = ~latplot,
             popup = ~paste(Year, "test", pilotdata %>% 
  leaflet() %>% 
  addTiles()  %>%  
  addMarkers(lng = ~lngplot,
             lat = ~latplot,
             popup = ~paste(Year, "test", Country))  ))  

```

```{r}
pilotdata %>% 
  head() %>% 
  mutate(test = paste(Year, Country)) %>% select(test, Year, Country) 

pilotdata %>% 
  head() %>% 
  mutate(test = paste(Year, Citation, Country)) %>% 
  leaflet() %>% 
  addTiles()  %>%  
  addMarkers(lng = ~lngplot,
             lat = ~latplot,
            popup = ~htmlEscape(test))


```

```{r}
pilotdata %>%
  mutate(test = paste(Year, Country, Citation)) %>% 
  leaflet() %>% 
  addTiles()  %>%  
  addMarkers(lng = ~lngplot,
             lat = ~latplot,
             popup = ~htmlEscape(test))
```


