---
title: "How to use Evitlas"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How_to_use_Evitlas}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## About EviAtlas

EviAtlas is an Open Source tool for creating and hosting visualisations from databases of studies created within systematic maps and systematic reviews. The tool was created as part of the ongoing Evidence Synthesis Hackathon series of events (www.evidencesynthesishackathon.com) aimed at producing free-to-use tools to support systematic reviews and maps across disciplines.


EviAtlas allows users to create a suite of visualisations from a database of studies, including Evidence Atlases (interactive geographical maps showing studies and their details over space), Heat Maps (cross tabulations of categorical variables that highlight clusters and gaps in the evidence), descriptive plots that help to visualise the evidence base (e.g. the number of publications per year), and human-readable databases that are easily filterable.


EviAtlas is built on coding written in R (https://www.r-project.org) and uses a Shiny App to provide a web-based user interface. As we develop the app further, we will provide source code to allow R users to further refine their visualisations.


## Systematic Maps and Systematic Reviews

Systematic maps and reviews are rigorous, comprehensive, transparent and repeatable methods for reviewing research literature on a particular topic. Systematic maps are overviews of nature of an evidence base relevant to a broad (open) question of policy or management relevance. Systematic reviews are detailed analyses of the findings of a group of similar studies, for example examining the effectiveness of an intervention or the impact of a factor. More information about systematic reviews and maps can be found for the following disciplines: environment, social welfare and international development, healthcare.


During the process of conducting a systematic map or systematic review, researchers typically produce a detailed database of relevant studies that includes various columns of descriptive information. Some of this data may be rich, textual descriptions (meta-data), and some of it may be categorical or numerical data (coding or quantitative data). Coding (for example different levels of a factor; high, medium, low, or different country names) allows a database to be easily filtered and searched, and allows the production of interactive visualisations of the evidence base to examine what research has been conducted, when, where, how, by whom, etc.. EviAtlas is the first Open Source tool that allows users to produce a range of different visualisations for their systematic reviews and maps.

## How EviAtlas Works

Upload a systematic review dataset (csv format) using the panel on the right, and then use the left sidebar to view a systematic map generated from your dataset, as well as some common plots used in systematic reviews.


Please ensure that your database is formatted in the correct way - column labels should all appear in the first row. To create an Evidence Atlas you will need one column with latitude data and one with longitude data; you can select these spatial variables in the Evidence Atlas pane. Please provide the lat/long in decimal degrees. In the future we hope to provide tools to recognise multiple coordinate types. If you have categorical variables that you wish to cross-tabulate in a Heat Map or other visualisation, EviAtlas currently requires that you store these categories in a single column. In the future we hope to integrate tidy principles that will allow you to aggregate and disaggregate complex data automatically.


Please use the example dataset to see what EviAtlas can do!

## How to Cite EviAtlas

Haddaway NR, Feierman A, Grainger M, Gray C, Tanriver-Ayder E, Dhaubanjar S, Westgate M. EviAtlas: a tool for visualising evidence synthesis databases. Environmental Evidence. 2019; 8:22. https://doi.org/10.1186/s13750-019-0167-1